// Generated by Selenium IDE
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Interactions;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading;
using Xunit;

namespace CreditCards.MyUITest
{
    public class SuiteTests : IDisposable
    {
        public IWebDriver driver { get; private set; }
        public IDictionary<String, Object> vars { get; private set; }
        public IJavaScriptExecutor js { get; private set; }
        public SuiteTests()
        {
            driver = new ChromeDriver();
            js = (IJavaScriptExecutor)driver;
            vars = new Dictionary<String, Object>();
        }
        public void Dispose()
        {
            driver.Quit();
        }

        [Fact]
        public void InputFormCredit()
        {

            driver.Navigate().GoToUrl("https://localhost:7014/");
            driver.Manage().Window.Size = new System.Drawing.Size(972, 524);

            Helpers.Pause();

            driver.FindElement(By.LinkText("Apply Now!")).Click();

            Helpers.Pause();

            driver.FindElement(By.Id("FirstName")).Click();

            Helpers.Pause();

            driver.FindElement(By.Id("FirstName")).SendKeys("Erick");
            driver.FindElement(By.Id("LastName")).SendKeys("Kurniawan");

            Helpers.Pause();

            driver.FindElement(By.Id("FrequentFlyerNumber")).Click();
            driver.FindElement(By.Id("Age")).SendKeys("2");
            driver.FindElement(By.Id("GrossAnnualIncome")).Click();
            driver.FindElement(By.Id("GrossAnnualIncome")).SendKeys("10000");
            driver.FindElement(By.Id("FrequentFlyerNumber")).Click();
            driver.FindElement(By.Id("FrequentFlyerNumber")).SendKeys("9999");
            driver.FindElement(By.CssSelector(".radio:nth-child(2) > .radio-inline")).Click();
            driver.FindElement(By.Id("BusinessSource")).Click();
            {
                var dropdown = driver.FindElement(By.Id("BusinessSource"));
                dropdown.FindElement(By.XPath("//option[. = 'Word of Mouth']")).Click();
            }
            driver.FindElement(By.Id("TermsAccepted")).Click();
            driver.FindElement(By.Id("SubmitApplication")).Click();
            Assert.Equal(driver.FindElement(By.CssSelector(".validation-summary-errors li")).Text, "You must be at least 18 years old");
        }
    }
}

